[package]
name = "cargo-demo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cargo-demo"
path = "src/main.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[[example]]
name = "basic"
path = "examples/basic.rs"
